[package]
name = "ext-host"
version = "0.0.1"
publish = false
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lib]
path = "src/extension_host.rs"

[dependencies]