package raykit:extension;

world extension {

    use commands.{command};

    export activate: func();

    export deactivate: func();

    export run-commands: func();

    import send-command: func(cmd: command);

    import get-commands: func();

    import get-settings: func();
}

interface commands {
    record command {
        name: string,
    }
}
